apiVersion: networking.k8s.io/v1  
kind: Ingress
metadata:  
  name: {{ .Chart.Name }}-ingress
  annotations:   
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:  
  rules:
    - host: {{ .Chart.Name }}
      http:
        paths:
          - path: /
            pathType: Prefix   
            backend:
              service:
                name:  {{ .Chart.Name }}-service
                port:
                  number: 80