apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-provider
  template:
    metadata:
      labels:
        app: payment-provider
    spec:
      containers:
      - name: main
        image: payment-provider:challenge
        imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: true
