apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice-app
  template:
    metadata:
      labels:
        app: invoice-app
    spec:
      containers:
      - name: main
        image: invoice-app:challenge
        imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: true
